/* =============================================================================
   Barbell — mockData
   The single source of seeded truth. Every screen reads from here.
   Edit this file to change the demo; nothing else holds data.
   Family office: Namsan Family Office. Reference date: 2026-09-19.
   ============================================================================= */
(function () {
  const KRW = 1383;            // ₩ per $1 — used for the secondary KRW line everywhere
  const TODAY = "2026-09-19";

  const family = {
    name: "Namsan Family Office",
    established: 1998,
    baseCurrency: "USD",
    reportingCurrency: "KRW",
    fx: KRW,
    asOf: "2026-09-19T15:42:00+09:00",
    totalAUM: 62400000,
    coreTarget: 0.9,
    alphaTarget: 0.1,
    operatingCompany: "Hanmi Chemical Holdings Co., Ltd.",
  };

  const accounts = {
    principal: {
      id: "principal",
      mode: "Sovereign Mode",
      name: "Y.S. Park",
      title: "Chairman · Principal",
      age: 68,
      mandate: "Capital preservation",
      scope: "Acts on the whole portfolio · has the final say on proposals",
      desc: "Buys, sells and commits anywhere in the book, and sets the objective everything else is measured against. Anything the successor wants to do beyond their own sleeve arrives here first.",
    },
    successor: {
      id: "successor",
      mode: "Successor Mode",
      name: "Jae-won Park",
      title: "Director · Successor",
      age: 34,
      mandate: "Growth",
      scope: "Acts inside the Alpha sleeve · proposes anything beyond it",
      desc: "A free hand with the 10% Alpha sleeve — no permission needed. The other 90% is fully visible but not theirs to move; acting on it means sending the Principal a proposal.",
    },
  };

  /* ---------------------------------------------------------------- taxonomy */
  const classes = [
    { key: "equity", label: "Equity", target: 35.0, sw: "sw-eq", color: "#1B2A4A" },
    { key: "debt", label: "Debt", target: 40.0, sw: "sw-dt", color: "#3F7183" },
    { key: "real", label: "Real Assets", target: 18.0, sw: "sw-ra", color: "#9A7B2E" },
    { key: "cash", label: "Cash Equivalents", target: 7.0, sw: "sw-cs", color: "#A9A396" },
  ];

  const subs = [
    { key: "pubeq", cls: "equity", label: "Public Equity", target: 24.0, note: "KR listed · US listed · ETFs" },
    { key: "pe", cls: "equity", label: "Private Equity", target: 4.5, note: "Buyout co-invest · growth" },
    { key: "vc", cls: "equity", label: "Venture Capital", target: 4.0, note: "Funds · direct SPVs" },
    { key: "preipo", cls: "equity", label: "Pre-IPO Secondaries", target: 2.5, note: "Late-stage blocks" },
    { key: "sov", cls: "debt", label: "Sovereign", target: 16.0, note: "UST · KTB" },
    { key: "ig", cls: "debt", label: "Investment Grade Credit", target: 9.0, note: "Corporate IG" },
    { key: "pcred", cls: "debt", label: "Private Credit / Direct Lending", target: 11.0, note: "Senior secured · direct" },
    { key: "struct", cls: "debt", label: "Structured", target: 4.0, note: "Notes · autocall" },
    { key: "re", cls: "real", label: "Real Estate", target: 9.0, note: "Direct · funds" },
    { key: "infra", cls: "real", label: "Infrastructure", target: 6.5, note: "Incl. data centers" },
    { key: "comm", cls: "real", label: "Commodities", target: 2.5, note: "Bullion · resources" },
    { key: "mmf", cls: "cash", label: "MMF", target: 2.5, note: "" },
    { key: "tbill", cls: "cash", label: "T-Bills", target: 1.5, note: "" },
    { key: "dep", cls: "cash", label: "Bank Deposits", target: 2.0, note: "" },
    { key: "fx", cls: "cash", label: "FX Balances", target: 1.0, note: "" },
  ];

  /* --------------------------------------------------------------- positions */
  /* prov: live | hanwha | self      liq: Daily | Quarterly | Locked            */
  const positions = [
    /* ---- EQUITY · Public (12) ------------------------------------------- */
    { id: "p01", name: "Hanmi Chemical Holdings Co., Ltd.", ticker: "004370.KS", cls: "equity", sub: "pubeq", grp: "KR listed",
      sleeve: "core", prov: "live", value: 4243219, cost: 2610000, qty: 29865, px: 196500, ccy: "KRW", pxUsd: 142.08, chg: 0.82,
      sector: "Materials", geo: "Korea", liq: "Daily", acquired: "2009-06-12", realizedYTD: 0, affiliate: true,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B14" },
      note: "Family operating company. Board seat held by the Principal." },
    { id: "p02", name: "Samsung Electronics Co., Ltd.", ticker: "005930.KS", cls: "equity", sub: "pubeq", grp: "KR listed",
      sleeve: "core", prov: "live", value: 1979838, cost: 1452000, qty: 37250, px: 73500, ccy: "KRW", pxUsd: 53.15, chg: -0.41,
      sector: "Info Tech", geo: "Korea", liq: "Daily", acquired: "2016-03-02", realizedYTD: 84000,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B15" } },
    { id: "p03", name: "SK hynix Inc.", ticker: "000660.KS", cls: "equity", sub: "pubeq", grp: "KR listed",
      sleeve: "core", prov: "live", value: 859908, cost: 498000, qty: 6090, px: 195300, ccy: "KRW", pxUsd: 141.20, chg: 1.94,
      sector: "Info Tech", geo: "Korea", liq: "Daily", acquired: "2021-11-08", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B16" } },
    { id: "p04", name: "NVIDIA Corporation", ticker: "NVDA", cls: "equity", sub: "pubeq", grp: "US listed",
      sleeve: "core", prov: "live", value: 2140000, cost: 742000, qty: 10000, px: 214.00, ccy: "USD", pxUsd: 214.00, chg: 1.12,
      sector: "Info Tech", geo: "United States", liq: "Daily", acquired: "2022-10-14", realizedYTD: 312000,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B21" } },
    { id: "p05", name: "Microsoft Corporation", ticker: "MSFT", cls: "equity", sub: "pubeq", grp: "US listed",
      sleeve: "core", prov: "live", value: 1619379, cost: 1104000, qty: 3330, px: 486.30, ccy: "USD", pxUsd: 486.30, chg: 0.34,
      sector: "Info Tech", geo: "United States", liq: "Daily", acquired: "2020-05-19", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B22" } },
    { id: "p06", name: "Apple Inc.", ticker: "AAPL", cls: "equity", sub: "pubeq", grp: "US listed",
      sleeve: "core", prov: "live", value: 1180800, cost: 861000, qty: 4500, px: 262.40, ccy: "USD", pxUsd: 262.40, chg: -0.28,
      sector: "Info Tech", geo: "United States", liq: "Daily", acquired: "2019-08-07", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B23" } },
    { id: "p07", name: "Alphabet Inc. Class A", ticker: "GOOGL", cls: "equity", sub: "pubeq", grp: "US listed",
      sleeve: "alpha", prov: "live", value: 690305, cost: 488000, qty: 3260, px: 211.75, ccy: "USD", pxUsd: 211.75, chg: 0.61,
      sector: "Comm Services", geo: "United States", liq: "Daily", acquired: "2024-02-21", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B24" } },
    { id: "p08", name: "Taiwan Semiconductor Mfg. (ADR)", ticker: "TSM", cls: "equity", sub: "pubeq", grp: "US listed",
      sleeve: "core", prov: "live", value: 739475, cost: 412000, qty: 2750, px: 268.90, ccy: "USD", pxUsd: 268.90, chg: 1.47,
      sector: "Info Tech", geo: "Taiwan", liq: "Daily", acquired: "2023-01-30", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B25" } },
    { id: "p09", name: "Toyota Motor Corporation", legacy: "TOYOTA (JPY口座) — 東証", ticker: "7203.T", cls: "equity", sub: "pubeq", grp: "US listed",
      sleeve: "core", prov: "live", value: 676800, cost: 585000, qty: 30000, px: 3320, ccy: "JPY", pxUsd: 22.56, chg: -0.62,
      sector: "Consumer Disc.", geo: "Japan", liq: "Daily", acquired: "2018-09-11", realizedYTD: 0, fxFlag: true,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet2!D7" },
      note: "JPY-denominated. Held in the Japan sub-account since the 2018 restructuring." },
    { id: "p10", name: "iShares MSCI ACWI ETF", ticker: "ACWI", cls: "equity", sub: "pubeq", grp: "ETF",
      sleeve: "core", prov: "live", value: 1340052, cost: 1088000, qty: 9665, px: 138.65, ccy: "USD", pxUsd: 138.65, chg: 0.22,
      sector: "Diversified", geo: "Global", liq: "Daily", acquired: "2021-04-06", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B31" } },
    { id: "p11", name: "Vanguard S&P 500 ETF", ticker: "VOO", cls: "equity", sub: "pubeq", grp: "ETF",
      sleeve: "core", prov: "live", value: 1111506, cost: 806000, qty: 1815, px: 612.40, ccy: "USD", pxUsd: 612.40, chg: 0.19,
      sector: "Diversified", geo: "United States", liq: "Daily", acquired: "2022-01-18", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B32" } },
    { id: "p12", name: "KODEX 200 ETF", ticker: "069500.KS", cls: "equity", sub: "pubeq", grp: "ETF",
      sleeve: "core", prov: "live", value: 520020, cost: 461000, qty: 16050, px: 44800, ccy: "KRW", pxUsd: 32.40, chg: 0.44,
      sector: "Diversified", geo: "Korea", liq: "Daily", acquired: "2023-07-25", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B33" } },

    /* ---- EQUITY · Private (7) ------------------------------------------- */
    { id: "p13", name: "Woori Industrial Buyout Co-Invest II", cls: "equity", sub: "pe", grp: "Buyout co-invest",
      sleeve: "core", prov: "hanwha", value: 1848698, cost: 1400000, ccy: "USD", liq: "Locked", term: "2029 wind-down",
      sector: "Industrials", geo: "Korea", asOf: "2026-06-30", acquired: "2022-05-18", onBarbell: true, vintage: "2022",
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A4" },
      note: "Hanwha-originated. Capital account pushed from the platform." },
    { id: "p14", name: "Sunrise Growth Partners IV, L.P.", cls: "equity", sub: "pe", grp: "Growth",
      sleeve: "alpha", prov: "hanwha", value: 1220000, cost: 950000, ccy: "USD", liq: "Locked", term: "2031 term",
      sector: "Diversified", geo: "United States", asOf: "2026-06-30", acquired: "2023-09-01", onBarbell: true, vintage: "2023",
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A5" } },
    { id: "p15", name: "Foundry Venture Partners VII, L.P.", cls: "equity", sub: "vc", grp: "Funds",
      sleeve: "alpha", prov: "hanwha", value: 1050000, cost: 900000, ccy: "USD", liq: "Locked", term: "2033 term",
      sector: "Technology", geo: "United States", asOf: "2026-06-30", acquired: "2024-03-14", onBarbell: true, vintage: "2024",
      unfunded: 1400000,
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A6" } },
    { id: "p16", name: "Daol Ventures Korea Fund III", cls: "equity", sub: "vc", grp: "Funds",
      sleeve: "alpha", prov: "hanwha", value: 680000, cost: 600000, ccy: "USD", liq: "Locked", term: "2032 term",
      sector: "Technology", geo: "Korea", asOf: "2026-06-30", acquired: "2023-02-09", onBarbell: true, vintage: "2023",
      unfunded: 320000,
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A7" } },
    { id: "p17", name: "Helios AI Infrastructure SPV I", cls: "equity", sub: "vc", grp: "Direct SPV",
      sleeve: "alpha", prov: "hanwha", value: 540000, cost: 400000, ccy: "USD", liq: "Locked", term: "Exit-driven",
      sector: "Technology", geo: "United States", asOf: "2026-06-30", acquired: "2026-05-22", onBarbell: true, vintage: "2026",
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A8" } },
    { id: "p18", name: "Aeris Aerospace — Series F secondary block", cls: "equity", sub: "preipo", grp: "Pre-IPO",
      sleeve: "alpha", prov: "hanwha", value: 820000, cost: 640000, ccy: "USD", liq: "Locked", term: "Until listing",
      sector: "Aerospace", geo: "United States", asOf: "2026-08-31", acquired: "2025-01-16", onBarbell: true, vintage: "2025",
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A9" } },
    { id: "p19", name: "Viva Republica (Toss) common — 2023 block", legacy: "비바리퍼블리카 구주 (2023년 매입)", cls: "equity", sub: "preipo", grp: "Pre-IPO",
      sleeve: "alpha", prov: "self", value: 440000, cost: 440000, ccy: "USD", liq: "Locked", term: "Until listing",
      sector: "Fintech", geo: "Korea", asOf: "2026-03-31", acquired: "2023-06-30", onBarbell: false, vintage: "2023",
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Sheet3!C22" },
      note: "Self-maintained. No NAV received since Q1 2026." },

    /* ---- DEBT · Public (6) ---------------------------------------------- */
    { id: "p20", name: "US Treasury 4.25% 15-Nov-2034", ticker: "US91282CLM1", cls: "debt", sub: "sov", grp: "Sovereign",
      sleeve: "core", prov: "live", value: 3180763, cost: 3102000, qty: 3265000, px: 97.42, ccy: "USD", pxUsd: 0.9742, chg: 0.11,
      sector: "Government", geo: "United States", liq: "Daily", acquired: "2024-11-20", realizedYTD: 0, ytm: 4.41, dur: 6.9,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B44" } },
    { id: "p21", name: "US Treasury 3.875% 15-Aug-2029", ticker: "US912828YB0", cls: "debt", sub: "sov", grp: "Sovereign",
      sleeve: "core", prov: "live", value: 2140102, cost: 2118000, qty: 2165000, px: 98.85, ccy: "USD", pxUsd: 0.9885, chg: 0.06,
      sector: "Government", geo: "United States", liq: "Daily", acquired: "2023-08-24", realizedYTD: 0, ytm: 4.14, dur: 2.7,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B45" } },
    { id: "p22", name: "Korea Treasury Bond 3.25% 10-Sep-2032", legacy: "국고03250-3209(22-8)", ticker: "KR103502GC93", cls: "debt", sub: "sov", grp: "Sovereign",
      sleeve: "core", prov: "live", value: 2041772, cost: 1994000, qty: 2120000, px: 96.31, ccy: "KRW", pxUsd: 0.9631, chg: -0.04,
      sector: "Government", geo: "Korea", liq: "Daily", acquired: "2022-09-15", realizedYTD: 0, ytm: 3.62, dur: 5.4,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B46" } },
    { id: "p23", name: "Apple Inc. 3.85% 04-May-2043", ticker: "US037833AT7", cls: "debt", sub: "ig", grp: "Corporate IG",
      sleeve: "core", prov: "live", value: 2410038, cost: 2520000, qty: 2865000, px: 84.12, ccy: "USD", pxUsd: 0.8412, chg: 0.21,
      sector: "Info Tech", geo: "United States", liq: "Daily", acquired: "2021-06-11", realizedYTD: 0, ytm: 5.02, dur: 11.4, rating: "AA+",
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B51" } },
    { id: "p24", name: "SK Telecom 4.45% 21-Mar-2031", ticker: "US78440PAC3", cls: "debt", sub: "ig", grp: "Corporate IG",
      sleeve: "core", prov: "live", value: 2382416, cost: 2360000, qty: 2440000, px: 97.64, ccy: "USD", pxUsd: 0.9764, chg: 0.09,
      sector: "Comm Services", geo: "Korea", liq: "Daily", acquired: "2024-04-02", realizedYTD: 0, ytm: 4.92, dur: 3.9, rating: "A-",
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B52" } },
    { id: "p25", name: "Hanwha TotalEnergies Petrochemical 4.10% 2028", ticker: "KR6008921D28", cls: "debt", sub: "ig", grp: "Corporate IG",
      sleeve: "core", prov: "live", value: 2069988, cost: 2050000, qty: 2085000, px: 99.28, ccy: "KRW", pxUsd: 0.9928, chg: 0.02,
      sector: "Materials", geo: "Korea", liq: "Daily", acquired: "2025-03-18", realizedYTD: 0, ytm: 4.28, dur: 1.9, rating: "A",
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B53" } },

    /* ---- DEBT · Private (4) --------------------------------------------- */
    { id: "p26", name: "Northgate Data Center Credit Facility (Senior Secured)", cls: "debt", sub: "pcred", grp: "Direct lending",
      sleeve: "core", prov: "hanwha", value: 2394921, cost: 2300000, ccy: "USD", liq: "Locked", term: "5yr · matures 2029",
      sector: "Infrastructure", geo: "United States", asOf: "2026-08-31", acquired: "2024-06-28", onBarbell: true, vintage: "2024",
      ytm: 9.10, rating: "Unrated (senior secured)",
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A12" } },
    { id: "p27", name: "Meridian Direct Lending Fund II", cls: "debt", sub: "pcred", grp: "Direct lending",
      sleeve: "core", prov: "hanwha", value: 1320000, cost: 1250000, ccy: "USD", liq: "Quarterly", term: "Quarterly with 90d notice",
      sector: "Diversified", geo: "United States", asOf: "2026-06-30", acquired: "2023-11-30", onBarbell: true, vintage: "2023",
      ytm: 8.40,
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A13" } },
    { id: "p28", name: "Seongsu redevelopment bridge loan", legacy: "성수동 개인대여금 (김부장 건)", cls: "debt", sub: "pcred", grp: "Direct lending",
      sleeve: "core", prov: "self", value: 780000, cost: 780000, ccy: "KRW", liq: "Locked", term: "Matures 2027-03",
      sector: "Real Estate", geo: "Korea", asOf: "2026-02-10", acquired: "2024-03-05", onBarbell: false,
      ytm: 7.50,
      src: { file: "부동산_임대현황.xlsx", cell: "Sheet1!F19" },
      note: "Legacy spreadsheet entry. Interest received in cash; principal unverified since February." },
    { id: "p29", name: "Hanwha Securities ELS 2024-11 (KOSPI200 / S&P 500 autocall)", cls: "debt", sub: "struct", grp: "Structured",
      sleeve: "core", prov: "hanwha", value: 2500000, cost: 2400000, ccy: "KRW", liq: "Quarterly", term: "3yr · autocall obs. quarterly",
      sector: "Structured", geo: "Korea", asOf: "2026-09-15", acquired: "2024-11-12", onBarbell: true, vintage: "2024",
      ytm: 6.80,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B61" } },

    /* ---- REAL ASSETS (6) ------------------------------------------------- */
    { id: "p30", name: "Teheran-ro office — floors 3–4, Gangnam", legacy: "강남 테헤란로 빌딩 3,4층 (본사옆)", cls: "real", sub: "re", grp: "Direct",
      sleeve: "core", prov: "self", value: 4100000, cost: 2850000, ccy: "KRW", liq: "Locked", term: "Direct title",
      sector: "Office", geo: "Korea", asOf: "2026-08-31", acquired: "2011-04-01", onBarbell: false,
      yieldPct: 4.2,
      src: { file: "부동산_임대현황.xlsx", cell: "Sheet1!B4" },
      note: "Appraisal-based. Last third-party valuation August 2026." },
    { id: "p31", name: "Yongsan residential — leased unit", legacy: "용산 아파트 (임대중) — 2호", cls: "real", sub: "re", grp: "Direct",
      sleeve: "core", prov: "self", value: 1850000, cost: 1320000, ccy: "KRW", liq: "Locked", term: "Direct title",
      sector: "Residential", geo: "Korea", asOf: "2026-05-20", acquired: "2014-10-20", onBarbell: false,
      yieldPct: 2.6,
      src: { file: "부동산_임대현황.xlsx", cell: "Sheet1!B12" } },
    { id: "p32", name: "Hanwha Korea Logistics REIT Co-Invest", cls: "real", sub: "re", grp: "Funds",
      sleeve: "core", prov: "hanwha", value: 1620000, cost: 1500000, ccy: "KRW", liq: "Locked", term: "2030 exit",
      sector: "Logistics", geo: "Korea", asOf: "2026-06-30", acquired: "2026-01-10", onBarbell: true, vintage: "2026",
      yieldPct: 6.1,
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A16" } },
    { id: "p33", name: "Pacific Core Real Estate Fund IV", cls: "real", sub: "re", grp: "Funds",
      sleeve: "core", prov: "hanwha", value: 1780000, cost: 1700000, ccy: "USD", liq: "Quarterly", term: "Open-end, quarterly queue",
      sector: "Diversified RE", geo: "Asia-Pacific", asOf: "2026-06-30", acquired: "2022-11-04", onBarbell: true, vintage: "2022",
      unfunded: 700000, yieldPct: 4.8,
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A17" } },
    { id: "p34", name: "Songdo Hyperscale Data Center Platform", cls: "real", sub: "infra", grp: "Infrastructure",
      sleeve: "core", prov: "hanwha", value: 2340000, cost: 2100000, ccy: "USD", liq: "Locked", term: "2034 concession",
      sector: "Data Centers", geo: "Korea", asOf: "2026-06-30", acquired: "2025-02-27", onBarbell: true, vintage: "2025",
      yieldPct: 7.4,
      src: { file: "PE_Capital_Calls_v7_FINAL.xlsx", cell: "Fund List!A18" } },
    { id: "p35", name: "Gold bullion — KRX custody account", cls: "real", sub: "comm", grp: "Commodities",
      sleeve: "core", prov: "live", value: 1410000, cost: 980000, qty: 340, px: 5735000, ccy: "KRW", pxUsd: 4147.06, chg: 0.37,
      sector: "Precious Metals", geo: "Korea", liq: "Daily", acquired: "2020-08-19", realizedYTD: 0,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B72" } },

    /* ---- CASH (7) -------------------------------------------------------- */
    { id: "p36", name: "Samsung KRW Money Market Fund", cls: "cash", sub: "mmf", grp: "MMF",
      sleeve: "core", prov: "live", value: 1010000, cost: 1010000, ccy: "KRW", liq: "Daily", sector: "Cash", geo: "Korea",
      acquired: "2026-01-05", ytm: 3.05, src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B80" } },
    { id: "p37", name: "Mirae Asset USD Money Market Fund", cls: "cash", sub: "mmf", grp: "MMF",
      sleeve: "alpha", prov: "live", value: 760000, cost: 760000, ccy: "USD", liq: "Daily", sector: "Cash", geo: "United States",
      acquired: "2026-02-12", ytm: 4.18, dryPowder: true,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B81" },
      note: "Alpha sleeve dry powder." },
    { id: "p38", name: "US Treasury Bill — 4 week", ticker: "US912797MK2", cls: "cash", sub: "tbill", grp: "T-Bills",
      sleeve: "core", prov: "live", value: 981257, cost: 979000, qty: 985000, px: 99.62, ccy: "USD", pxUsd: 0.9962, chg: 0.01,
      sector: "Government", geo: "United States", liq: "Daily", acquired: "2026-09-04", ytm: 4.22,
      src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B82" } },
    { id: "p39", name: "KEB Hana Bank — KRW time deposit", cls: "cash", sub: "dep", grp: "Deposits",
      sleeve: "core", prov: "live", value: 858743, cost: 858743, ccy: "KRW", liq: "Daily", sector: "Cash", geo: "Korea",
      acquired: "2026-04-30", ytm: 3.40, src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B83" } },
    { id: "p40", name: "Citibank N.A. — USD demand deposit", cls: "cash", sub: "dep", grp: "Deposits",
      sleeve: "core", prov: "live", value: 520000, cost: 520000, ccy: "USD", liq: "Daily", sector: "Cash", geo: "United States",
      acquired: "2025-12-01", ytm: 0.85, src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B84" } },
    { id: "p41", name: "FX balance — JPY", cls: "cash", sub: "fx", grp: "FX",
      sleeve: "core", prov: "live", value: 158000, cost: 165000, ccy: "JPY", liq: "Daily", sector: "Cash", geo: "Japan",
      acquired: "2025-06-18", fxFlag: true, src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet2!D19" } },
    { id: "p42", name: "FX balance — EUR", cls: "cash", sub: "fx", grp: "FX",
      sleeve: "core", prov: "live", value: 92000, cost: 90000, ccy: "EUR", liq: "Daily", sector: "Cash", geo: "Europe",
      acquired: "2025-06-18", fxFlag: true, src: { file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet2!D20" } },
  ];


  /* ------------------------------------------------------------- onboarding */
  const uploadFiles = [
    { id: "f1", name: "Holdings_Master_2026Q3.xlsx", size: "412 KB", sheets: 4, rows: 63, note: "Custodian export, hand-edited" },
    { id: "f2", name: "PE_Capital_Calls_v7_FINAL.xlsx", size: "188 KB", sheets: 3, rows: 41, note: "Maintained by the family CFO" },
    { id: "f3", name: "부동산_임대현황.xlsx", size: "96 KB", sheets: 2, rows: 22, note: "Rental schedule, KRW, no headers" },
  ];

  const ingestSteps = ["Reading files", "Extracting positions", "Matching to securities", "Reconciling"];

  /* 7 deliberate exceptions. Everything else lands high-confidence. */
  const exceptions = [
    { id: "e1", kind: "Unmatched ticker", file: "Holdings_Master_2026Q3.xlsx", cell: "Sheet1!B14",
      raw: "HNMI CHEM (구) 보통주", qty: "29,865", conf: 0.41,
      issue: "Ticker string matches two listed securities. Cost basis suggests a 2009 acquisition.",
      type: "select", options: ["Hanmi Chemical Holdings Co., Ltd. · 004370.KS", "Hanmi Pharm Co., Ltd. · 128940.KS", "Create as unlisted holding"],
      answer: "Hanmi Chemical Holdings Co., Ltd. · 004370.KS" },
    { id: "e3", kind: "Duplicate across files", file: "PE_Capital_Calls_v7_FINAL.xlsx + 부동산_임대현황.xlsx", cell: "Fund List!A18 ↔ Sheet1!B22",
      raw: "Songdo Hyperscale DC Platform / 송도 데이터센터 지분", qty: "—", conf: 0.63,
      issue: "The same position appears in two files with values $2,340,000 and ₩3.24B ($2,342,733). Booking both would overstate assets by 3.8%.",
      type: "select", options: ["Merge — keep Hanwha-sourced NAV ($2,340,000)", "Merge — keep spreadsheet value (₩3.24B)", "Keep both (not recommended)"],
      answer: "Merge — keep Hanwha-sourced NAV ($2,340,000)" },
    { id: "e4", kind: "Ambiguous currency", file: "부동산_임대현황.xlsx", cell: "Sheet1!F19",
      raw: "성수동 개인대여금 (김부장 건)   1,080,000,000", qty: "—", conf: 0.38,
      issue: "No currency column on this sheet. 1,080,000,000 reads as KRW ($780,910) but the adjacent column is formatted as USD.",
      type: "select", options: ["KRW — ₩1.08B ≈ $780,000", "USD — $1,080,000,000", "USD — $1,080,000"],
      answer: "KRW — ₩1.08B ≈ $780,000" },
  ];

  /* ----------------------------------------------------------------- mandate */
  const mandates = [
    { key: "preservation", label: "Protect capital", core: 95, alpha: 5,
      line: "Sovereign duration and cash carry the book. Alternatives only where they are contractual and secured.",
      targets: { equity: 25, debt: 50, real: 17, cash: 8 } },
    { key: "balanced", label: "Fund the family", core: 90, alpha: 10,
      line: "Income first — private credit, property and investment grade credit pay the distributions.",
      targets: { equity: 35, debt: 40, real: 18, cash: 7 }, current: true },
    { key: "growth", label: "Grow the estate", core: 80, alpha: 20,
      line: "Total return, equity-led, with private growth alongside rather than instead of it.",
      targets: { equity: 46, debt: 28, real: 20, cash: 6 } },
  ];

  const survey = [
    { id: "q1", sharpens: "Sets how hard locked offerings are marked down in the marketplace", q: "Liquidity needed from the portfolio over the next 24 months",
      type: "select", options: ["None — external income covers spending", "Under $2M", "$2M – $5M", "Over $5M"], a: "$2M – $5M" },
    { id: "q2", sharpens: "Checked against the call schedule already read from your files", q: "Known capital calls already committed",
      type: "select", options: ["None", "Under $2M", "$2M – $6M", "Over $6M"], a: "$2M – $6M" },
    { id: "q3", sharpens: "Sets the level the concentration flag fires at", q: "Concentration in the family operating company",
      type: "select", options: ["Under 5% of assets", "5 – 10%", "10 – 25%", "Over 25%"], a: "5 – 10%",
      note: "Currently 6.8% — Hanmi Chemical Holdings." },
    { id: "q4", sharpens: "Decides which currency the return is decomposed against", q: "FX base currency for reporting and risk",
      type: "select", options: ["KRW", "USD", "USD with KRW reporting"], a: "USD with KRW reporting" },
    { id: "q5", sharpens: "Frames the holding-period observations on the Tax tab", q: "Tax residency",
      type: "select", options: ["Korea", "United States", "Dual KR / US", "Other"], a: "Korea" },
    { id: "q6", sharpens: "Bounds how far the model may tilt from the posture above", q: "Drawdown tolerance — the loss that would force a change of plan",
      type: "select", options: ["$3M (−4.8%)", "$6M (−9.6%)", "$12M (−19.2%)", "$19M (−30.4%)"], a: "$6M (−9.6%)",
      note: "Stated in dollars, not percentages, because that is how the decision is actually made." },
    { id: "q7", sharpens: "Sets how long an illiquid holding may reasonably lock up", q: "Generational transfer horizon",
      type: "select", options: ["Within 5 years", "5 – 10 years", "10 – 20 years", "No defined horizon"], a: "5 – 10 years" },
    { id: "q8", sharpens: "Removes those sectors from the marketplace entirely", q: "Prohibited sectors",
      type: "multi", options: ["Tobacco", "Gaming / casinos", "Defence", "Fossil fuel extraction", "Crypto-native"], a: ["Gaming / casinos", "Crypto-native"] },
  ];

  /* ------------------------------------------------------- model portfolios */
  const modelPortfolios = {
    "1m": { label: "$1M tier", subs: { pubeq: 38, pe: 0, vc: 2, preipo: 0, sov: 22, ig: 12, pcred: 3, struct: 0, re: 10, infra: 3, comm: 2, mmf: 4, tbill: 2, dep: 2, fx: 0 } },
    "10m": { label: "$10M tier", subs: { pubeq: 30, pe: 3, vc: 3, preipo: 1, sov: 18, ig: 10, pcred: 8, struct: 3, re: 10, infra: 5, comm: 2, mmf: 3, tbill: 2, dep: 2, fx: 0 } },
    "100m": { label: "$100M tier", subs: { pubeq: 22, pe: 6, vc: 5, preipo: 3, sov: 15, ig: 8, pcred: 12, struct: 4, re: 9, infra: 8, comm: 2, mmf: 2, tbill: 2, dep: 1, fx: 1 } },
  };

  /* The objective the family is optimising for. Each goal tilts the model by
     group — alternatives, liquid markets, cash — and equity against debt.
     Weights are renormalised to 100 after the tilt. */
  const ALT_SUBS = ["pe", "vc", "preipo", "pcred", "re", "infra"];
  /* One set of keys with `mandates` above: the posture stated in onboarding is
     the posture the model is drawn for.

     Each objective is a different SHAPE, not a different point on one risk
     ladder — tilts are per subcategory, so "fund the family" loads credit and
     property while "grow the estate" loads equity, and the two produce visibly
     different books rather than two doses of the same medicine.
     Anything unlisted stays at 1.0. */
  const modelGoals = [
    { key: "preservation", label: "Protect capital",
      tilt: { sov: 1.70, tbill: 1.60, dep: 1.50, mmf: 1.50, fx: 1.20, ig: 1.25, struct: 0.80,
              pcred: 0.65, re: 0.85, infra: 0.75, comm: 1.15, pubeq: 0.65, pe: 0.35, vc: 0.20, preipo: 0.15 } },
    { key: "balanced", label: "Fund the family", default: true,
      tilt: { pcred: 1.65, re: 1.45, infra: 1.40, ig: 1.35, struct: 1.20, sov: 0.90, tbill: 0.90, fx: 0.80,
              pubeq: 0.85, pe: 0.70, vc: 0.30, preipo: 0.25, comm: 0.60 } },
    { key: "growth", label: "Grow the estate",
      tilt: { pubeq: 1.50, pe: 1.35, vc: 1.35, preipo: 1.25, infra: 1.00, re: 0.80, sov: 0.55, ig: 0.70,
              pcred: 0.95, struct: 0.80, comm: 0.80, mmf: 0.70, tbill: 0.70, dep: 0.70, fx: 0.70 } },
  ];

  /* Long-run assumptions used only for the projection strip under the model.
     Nominal USD, before fees and tax. Stated on the chart, not hidden in code. */
  const expectedReturn = { equity: 7.5, debt: 5.0, real: 7.0, cash: 4.0 };
  const expectedVol = { equity: 18.0, debt: 5.0, real: 11.0, cash: 1.0 };
  /* Correlations between the four classes. Private holdings are marked
     quarterly, which understates their true correlation to listed markets;
     these are the economic figures, not the smoothed ones. */
  const classCorr = {
    equity: { equity: 1.0, debt: 0.10, real: 0.55, cash: 0.00 },
    debt:   { equity: 0.10, debt: 1.0, real: 0.25, cash: 0.10 },
    real:   { equity: 0.55, debt: 0.25, real: 1.0, cash: 0.00 },
    cash:   { equity: 0.00, debt: 0.10, real: 0.00, cash: 1.0 },
  };
  /* A class average assumes the class is held as an index. It is not: the book
     holds nine single names, one of them the family's own operating company.
     Specific risk on an individual equity, over and above its market. */
  const idiosyncraticVol = 45.0;

  /* --------------------------------------------------- calls & distributions */
  const capitalCalls = [
    { id: "cc1", fund: "Foundry Venture Partners VII, L.P.", pid: "p15", date: "2026-10-28", amount: 1100000, status: "Due" },
    { id: "cc2", fund: "Pacific Core Real Estate Fund IV", pid: "p33", date: "2026-11-12", amount: 700000, status: "Due" },
    { id: "cc3", fund: "Daol Ventures Korea Fund III", pid: "p16", date: "2027-01-20", amount: 320000, status: "Scheduled" },
    { id: "cc4", fund: "Foundry Venture Partners VII, L.P.", pid: "p15", date: "2027-02-15", amount: 1100000, status: "Scheduled" },
    { id: "cc5", fund: "Pacific Core Real Estate Fund IV", pid: "p33", date: "2027-02-28", amount: 700000, status: "Scheduled" },
    { id: "cc6", fund: "Songdo Hyperscale Data Center Platform", pid: "p34", date: "2027-03-05", amount: 2550000, status: "Scheduled" },
    { id: "cc7", fund: "Foundry Venture Partners VII, L.P.", pid: "p15", date: "2027-06-30", amount: 400000, status: "Projected" },
    { id: "cc8", fund: "Sunrise Growth Partners IV, L.P.", pid: "p14", date: "2027-09-15", amount: 450000, status: "Projected" },
    { id: "cc9", fund: "Daol Ventures Korea Fund III", pid: "p16", date: "2028-01-18", amount: 280000, status: "Projected" },
    { id: "cc10", fund: "Songdo Hyperscale Data Center Platform", pid: "p34", date: "2028-04-10", amount: 600000, status: "Projected" },
  ];

  const distributions = [
    { id: "d1", fund: "Woori Industrial Buyout Co-Invest II", date: "2026-12-15", amount: 480000, status: "Announced" },
    { id: "d2", fund: "Hanwha Securities ELS 2024-11", date: "2026-11-30", amount: 160000, status: "Coupon" },
    { id: "d3", fund: "Northgate Data Center Credit Facility", date: "2026-10-31", amount: 54000, status: "Coupon" },
    { id: "d4", fund: "Northgate Data Center Credit Facility", date: "2027-01-31", amount: 54000, status: "Coupon" },
    { id: "d5", fund: "Meridian Direct Lending Fund II", date: "2027-02-28", amount: 92000, status: "Projected" },
    { id: "d6", fund: "Woori Industrial Buyout Co-Invest II", date: "2027-06-30", amount: 640000, status: "Projected" },
    { id: "d7", fund: "Hanwha Korea Logistics REIT Co-Invest", date: "2027-04-30", amount: 120000, status: "Projected" },
    { id: "d8", fund: "Pacific Core Real Estate Fund IV", date: "2027-09-30", amount: 210000, status: "Projected" },
    { id: "d9", fund: "Aeris Aerospace — Series F block", date: "2028-03-31", amount: 900000, status: "Projected (listing)" },
    { id: "d10", fund: "Songdo Hyperscale Data Center Platform", date: "2028-06-30", amount: 340000, status: "Projected" },
  ];

  /* ------------------------------------------------------------ performance */
  const benchmark = { label: "60% MSCI ACWI / 40% Bloomberg Global Aggregate", hedgeable: true };

  const performance = {
    MTD: { port: 0.9, bench: 0.7, fx: -0.3, hedged: 1.2 },
    QTD: { port: 3.1, bench: 2.6, fx: -0.8, hedged: 3.9 },
    YTD: { port: 9.4, bench: 7.8, fx: 1.9, hedged: 7.5 },
    ITD: { port: 41.2, bench: 33.6, fx: 4.4, hedged: 36.8 },
  };

  const attribution = {
    MTD: [ { n: "NVIDIA Corporation", pp: 0.31 }, { n: "SK hynix Inc.", pp: 0.12 }, { n: "Hanmi Chemical Holdings", pp: 0.09 },
           { n: "US Treasury 4.25% 2034", pp: 0.04 }, { n: "Toyota Motor Corporation", pp: -0.06 }, { n: "Apple Inc.", pp: -0.04 } ],
    QTD: [ { n: "NVIDIA Corporation", pp: 1.02 }, { n: "Hanmi Chemical Holdings", pp: 0.58 }, { n: "SK hynix Inc.", pp: 0.41 },
           { n: "Songdo Hyperscale DC Platform", pp: 0.33 }, { n: "Apple Inc. 3.85% 2043", pp: -0.19 }, { n: "FX translation (KRW)", pp: -0.31 } ],
    YTD: [ { n: "NVIDIA Corporation", pp: 2.84 }, { n: "Hanmi Chemical Holdings", pp: 1.61 }, { n: "Aeris Aerospace block", pp: 0.72 },
           { n: "Songdo Hyperscale DC Platform", pp: 0.55 }, { n: "SK hynix Inc.", pp: 0.49 }, { n: "Apple Inc. 3.85% 2043", pp: -0.41 },
           { n: "Viva Republica (Toss) block", pp: -0.22 } ],
    ITD: [ { n: "Hanmi Chemical Holdings", pp: 9.40 }, { n: "NVIDIA Corporation", pp: 8.05 }, { n: "Teheran-ro office", pp: 4.10 },
           { n: "Microsoft Corporation", pp: 2.20 }, { n: "Apple Inc. 3.85% 2043", pp: -0.90 } ],
  };

  /* ---------------------------------------------------------- marketplace */
  /* One schema for everything. `kind` only changes the transaction mechanic. */
  const market = [
    /* ---- Sovereign / duration ---------------------------------------- */
    { id: "m01", kind: "listed", name: "US Treasury 4.125% 15-Aug-2036", ticker: "US91282CMR9", fills: "sov", cls: "debt",
      ret: "4.38% YTM", retNum: 4.38, liq: "Daily", term: "10yr", min: 10000, avail: "Continuous", fit: 94,
      why: "On-the-run 10-year — the deepest, most liquid way to hold long sovereign duration.",
      sector: "Government", geo: "United States", ccy: "USD", px: 99.31, chg: 0.08, ytm: 4.38, dur: 8.2, rating: "AA+",
      overview: "On-the-run 10-year Treasury. The fixed income sleeve carries a weighted duration of 5.2 years against a 7.5-year policy; this is the cleanest instrument for lengthening it.",
      terms: [["Settlement", "T+1"], ["Coupon", "4.125%, semi-annual"], ["Duration", "8.2 years"], ["Minimum", "$10,000 face"], ["Custody", "Hanwha Securities"]],
      docs: [["Offering circular", "PDF · 42pp"], ["Auction results", "PDF · 3pp"]],
      qa: [["Is this hedged to KRW?", "No. A KRW-hedged sleeve can be requested at the order ticket; the hedge is booked as a separate line."]] },
    { id: "m02", kind: "listed", name: "Korea Treasury Bond 3.375% 10-Sep-2036", ticker: "KR103502GJ44", fills: "sov", cls: "debt",
      ret: "3.71% YTM", retNum: 3.71, liq: "Daily", term: "10yr", min: 10000, avail: "Continuous", fit: 90,
      why: "KRW-denominated duration; matches the reporting currency without an FX overlay.",
      sector: "Government", geo: "Korea", ccy: "KRW", px: 97.88, chg: -0.03, ytm: 3.71, dur: 8.4, rating: "AA",
      overview: "Benchmark 10-year KTB. For a family reporting in KRW, sovereign duration held in the reporting currency removes the translation line that currently costs −0.8pp QTD.",
      terms: [["Settlement", "T+1"], ["Coupon", "3.375%, semi-annual"], ["Duration", "8.4 years"], ["Minimum", "₩10,000,000 face"], ["Custody", "Hanwha Securities"]],
      docs: [["Issue terms", "PDF · 18pp"]],
      qa: [["Withholding for a Korean resident?", "KTB interest is subject to standard Korean withholding. Barbell does not provide tax advice."]] },
    { id: "m03", kind: "listed", name: "iShares 7-10 Year Treasury Bond ETF", ticker: "IEF", fills: "sov", cls: "debt",
      ret: "4.21% yield", retNum: 4.21, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 88,
      why: "The whole 7–10 year Treasury curve in one order, 0.15%, daily liquidity.",
      sector: "Government", geo: "United States", ccy: "USD", px: 96.44, chg: 0.14, expense: 0.15, dur: 7.4,
      overview: "Index exposure to the 7–10 year Treasury curve. The cheapest way to add duration in a single ticket while a direct ladder is built out over subsequent quarters.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.15%"], ["Distribution", "Monthly"], ["Minimum", "1 share"], ["Custody", "Hanwha Securities"]],
      docs: [["Prospectus", "PDF · 88pp"], ["Fact sheet", "PDF · 2pp"]],
      qa: [["Why an ETF rather than the bonds?", "Speed. The ETF fills the gap this week; the direct ladder can replace it over two quarters without a further allocation decision."]] },
    { id: "m04", kind: "listed", name: "iShares 1-3 Year Treasury Bond ETF", ticker: "SHY", fills: "sov", cls: "debt",
      ret: "4.11% yield", retNum: 4.11, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 71,
      why: "Low duration and low volatility — a parking place for capital-call reserves, not a duration holding.",
      sector: "Government", geo: "United States", ccy: "USD", px: 82.90, chg: 0.02, expense: 0.15, dur: 1.9,
      overview: "Short-dated Treasuries. The natural landing place for the Q1 2027 capital call reserve.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.15%"], ["Duration", "1.9 years"], ["Minimum", "1 share"]],
      docs: [["Prospectus", "PDF · 88pp"]], qa: [] },
    { id: "m05", kind: "listed", name: "KOSEF 10Y KTB ETF", ticker: "148070.KS", fills: "sov", cls: "debt",
      ret: "3.58% yield", retNum: 3.58, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 82,
      why: "KRW duration in ETF form; settles in the domestic account already in use.",
      sector: "Government", geo: "Korea", ccy: "KRW", px: 118450, chg: 0.06, expense: 0.15, dur: 8.1,
      overview: "Domestic ETF tracking the 10-year KTB index. Settles in the existing Hanwha Securities KRW account with no new custody arrangement.",
      terms: [["Settlement", "T+2"], ["Expense ratio", "0.15%"], ["Minimum", "1 share"]],
      docs: [["투자설명서", "PDF · 64pp"]], qa: [] },

    { id: "m34", kind: "private", name: "Korea Housing Finance Corp — private placement MBS 2026-C", fills: "sov", cls: "debt",
      ret: "4.62% YTM", retNum: 4.62, liq: "Locked", term: "3 years", min: 500000, avail: "₩18B of ₩150B remaining", fit: 86,
      why: "Government-guaranteed KRW credit at a 91bp spread over the KTB curve, in exchange for holding to maturity.",
      sector: "Government", geo: "Korea", ccy: "KRW", manager: "Korea Housing Finance Corporation", closing: "2026-10-08",
      hanwha: true, anchor: "Hanwha Life holds ₩400B of the same programme across recent vintages.",
      overview: "Senior tranche of a government-guaranteed residential mortgage securitisation. Sovereign-equivalent credit with a 91bp pickup over the on-the-run KTB, in exchange for holding to maturity. Fills the duration gap in the reporting currency without an FX overlay.",
      terms: [["Yield to maturity", "4.62%"], ["Guarantee", "Korea Housing Finance Corporation (government-backed)"], ["Term", "3 years, no early redemption"], ["Minimum", "₩700,000,000 (≈$500,000)"], ["Coupon", "Quarterly"], ["Closing", "8 October 2026"]],
      docs: [["Programme prospectus", "PDF · 96pp"], ["Pool characteristics", "XLSX"], ["Guarantee terms", "PDF · 12pp"]],
      qa: [["Why is this on the same list as an ETF?", "Because it answers the same need. It pays 91bp more than the liquid alternative and cannot be sold for three years — that is a price and a term, not a separate category of product."]] },

    /* ---- Private credit ---------------------------------------------- */
    { id: "m06", kind: "private", name: "Northgate Data Center Credit Facility II", fills: "pcred", cls: "debt",
      ret: "9.2% target", retNum: 9.2, liq: "Locked", term: "5 years", min: 1000000, avail: "$4.2M of $60M remaining", fit: 96,
      why: "Senior secured against contracted data centre cash flows, on the same security package as the Facility I position already held.",
      sector: "Infrastructure", geo: "United States", ccy: "USD", manager: "Northgate Capital Partners", closing: "2026-10-30",
      hanwha: true, anchor: "Hanwha Life holds $180M of the senior tranche on identical terms.",
      overview: "Senior secured lending against a 220MW US hyperscale data center platform, 94% contracted to two investment-grade tenants on 12-year leases. First-lien on the operating entity, 55% LTV on an independent appraisal, cash sweep above 1.35x DSCR. The family already holds the Facility I position at $2.39M; this is the same borrower, same security package, one tranche later.",
      terms: [["Target return", "9.2% (SOFR + 475bps, 4.0% floor)"], ["Term", "5 years, no extension"], ["Security", "First lien, 55% LTV"], ["Minimum", "$1,000,000"], ["Distribution", "Quarterly cash"], ["Closing", "30 October 2026"], ["Fees", "1.0% management, no carry"]],
      docs: [["Information memorandum", "PDF · 64pp"], ["Credit agreement (draft)", "PDF · 212pp"], ["Third-party appraisal", "PDF · 38pp"], ["Tenant lease summary", "XLSX"]],
      qa: [["What happens if a tenant defaults?", "DSCR falls to 0.82x on a single-tenant default, triggering the cash sweep and a standstill. The appraisal supports 68% recovery at the first-lien level."],
           ["Can this be sold before maturity?", "Yes — positions originated on Barbell become listable on the secondary board after a 12-month hold."]] },
    { id: "m07", kind: "private", name: "Meridian Direct Lending Fund III", fills: "pcred", cls: "debt",
      ret: "8.4% target", retNum: 8.4, liq: "Quarterly", term: "Evergreen, 90d notice", min: 500000, avail: "Open", fit: 89,
      why: "8.4% target with quarterly liquidity; the family holds Fund II and the reporting line is identical.",
      sector: "Diversified", geo: "United States", ccy: "USD", manager: "Meridian Credit", closing: "Quarterly close",
      overview: "Diversified senior secured lending to sponsor-backed mid-market borrowers, 128 positions, average hold 1.4% of the fund. Evergreen structure with quarterly redemption at NAV subject to a 5% gate.",
      terms: [["Target return", "8.4% net"], ["Liquidity", "Quarterly, 90 days' notice, 5% gate"], ["Minimum", "$500,000"], ["Fees", "1.25% / 10% over 6%"], ["Leverage", "0.85x"]],
      docs: [["Private placement memorandum", "PDF · 118pp"], ["Q2 2026 investor letter", "PDF · 12pp"]],
      qa: [["How did the gate behave in 2024?", "Redemptions were met in full in every quarter since inception; the gate has never been applied."]] },
    { id: "m08", kind: "listed", name: "Invesco Senior Loan ETF", ticker: "BKLN", fills: "pcred", cls: "debt",
      ret: "7.60% yield", retNum: 7.6, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 76,
      why: "Floating-rate senior loans with daily liquidity — the same credit risk without the lock-up.",
      sector: "Diversified", geo: "United States", ccy: "USD", px: 20.88, chg: 0.05, expense: 0.65,
      overview: "Index exposure to the US leveraged loan market. Lower yield than direct lending and no origination premium, but it fills the credit gap immediately and can be sold to fund the Q1 2027 capital calls if needed.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.65%"], ["Distribution", "Monthly"], ["Minimum", "1 share"]],
      docs: [["Prospectus", "PDF · 92pp"]],
      qa: [["Why does this score below the private options?", "Fit weights the illiquidity premium. BKLN yields 7.6% against 9.2% for equivalent first-lien risk in the Northgate facility."]] },
    { id: "m09", kind: "listed", name: "Ares Capital Corporation", ticker: "ARCC", fills: "pcred", cls: "debt",
      ret: "9.1% dividend", retNum: 9.1, liq: "Daily", term: "Listed BDC", min: 1000, avail: "Continuous", fit: 74,
      why: "Direct-lending economics in listed form; carries equity-market beta the private facilities do not.",
      sector: "Financials", geo: "United States", ccy: "USD", px: 22.41, chg: -0.31,
      overview: "The largest listed business development company. Exposure to a $27bn senior secured loan book, priced daily and therefore volatile in a way the underlying loans are not.",
      terms: [["Settlement", "T+1"], ["Dividend", "Quarterly"], ["Premium / discount to NAV", "+4.2%"], ["Minimum", "1 share"]],
      docs: [["10-K 2025", "PDF · 214pp"], ["Q2 2026 supplement", "PDF · 28pp"]], qa: [] },
    { id: "m10", kind: "listed", name: "Hanwha Securities Floating Rate Note 2026-06", ticker: "HWFRN2606", fills: "pcred", cls: "debt",
      ret: "6.85% coupon", retNum: 6.85, liq: "Quarterly", term: "3yr · quarterly put", min: 100000, avail: "₩40B tranche open", fit: 80,
      why: "Floating KRW coupon with a quarterly put — credit-like yield without the ten-year lock.",
      sector: "Structured", geo: "Korea", ccy: "KRW", ytm: 6.85,
      hanwha: true, anchor: "Issued by Hanwha Securities; Hanwha Life holds ₩120B of the same series.",
      overview: "Senior unsecured floating rate note referencing 91-day CD + 285bps, with a quarterly investor put at par. Sits between the money market sleeve and private credit on both yield and liquidity.",
      terms: [["Coupon", "CD91 + 285bps, quarterly reset"], ["Put", "Quarterly at par, 10 business days' notice"], ["Minimum", "₩100,000,000"], ["Issuer rating", "A+ (KIS)"]],
      docs: [["Term sheet", "PDF · 8pp"], ["Issuer disclosure", "PDF · 46pp"]], qa: [] },

    /* ---- Infrastructure ---------------------------------------------- */
    { id: "m11", kind: "private", name: "Songdo Hyperscale Data Center Platform II", fills: "infra", cls: "real",
      ret: "13.5% target IRR", retNum: 13.5, liq: "Locked", term: "8 years", min: 750000, avail: "$11M of $140M remaining", fit: 93,
      why: "Second phase of an asset the family already owns, at the same entry basis as Hanwha Life.",
      sector: "Data Centers", geo: "Korea", ccy: "USD", manager: "Hanwha Asset Management", closing: "2026-11-14",
      hanwha: true, anchor: "Hanwha Life is the anchor investor at $220M, subscribed at the same price and terms as members.",
      overview: "Second phase of the Songdo campus: 180MW of contracted capacity with a signed 15-year offtake from a global cloud operator. Phase I, which the family already holds at $2.34M, is 100% leased and distributing at a 7.4% cash yield.",
      terms: [["Target IRR", "13.5% gross / 11.8% net"], ["Cash yield", "6.2% from year 3"], ["Term", "8 years"], ["Minimum", "$750,000"], ["Fees", "1.5% / 15% over 8%"], ["Closing", "14 November 2026"]],
      docs: [["Investment memorandum", "PDF · 88pp"], ["Offtake agreement summary", "PDF · 14pp"], ["Power supply agreement", "PDF · 22pp"], ["Phase I performance", "PDF · 9pp"]],
      qa: [["Is the power supply secured?", "A 20-year PPA with KEPCO covers 140MW; the balance is contracted through a private generator with a take-or-pay floor."],
           ["What is the concentration effect?", "Committing $750K takes data center exposure to 5.0% of total assets across Phase I, Phase II and the Northgate credit facility."]] },
    { id: "m12", kind: "private", name: "Hanwha Korea Logistics REIT Co-Invest II", fills: "infra", cls: "real",
      ret: "9.8% target IRR", retNum: 9.8, liq: "Locked", term: "6 years", min: 300000, avail: "$6M of $45M remaining", fit: 85,
      why: "$300,000 minimum, quarterly cash from year one; Co-Invest I is marking at 1.08x.",
      sector: "Logistics", geo: "Korea", ccy: "KRW", manager: "Hanwha Asset Management", closing: "2026-12-05",
      hanwha: true, anchor: "Hanwha Life holds 40% of the REIT's equity alongside co-investors.",
      overview: "Cold-chain and last-mile logistics assets in the Seoul metropolitan area, 91% occupied on a weighted 6.2-year lease term. Distributions quarterly from year 1.",
      terms: [["Target IRR", "9.8%"], ["Cash yield", "5.9% from year 1"], ["Term", "6 years"], ["Minimum", "$300,000"], ["Fees", "1.2% / 12% over 7%"], ["Closing", "5 December 2026"]],
      docs: [["Co-investment memorandum", "PDF · 52pp"], ["Asset schedule", "XLSX"], ["Valuation report", "PDF · 30pp"]],
      qa: [["How does this differ from Co-Invest I?", "Same manager and asset type; Co-Invest II adds three cold-chain facilities and excludes the Incheon site that anchored Fund I."]] },
    { id: "m13", kind: "listed", name: "Global X Data Center & Digital Infrastructure ETF", ticker: "DTCR", fills: "infra", cls: "real",
      ret: "8.5% est. total", retNum: 8.5, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 77,
      why: "The same theme as the two private data center positions, liquid, at a listed-market multiple.",
      sector: "Data Centers", geo: "Global", ccy: "USD", px: 18.62, chg: 0.74, expense: 0.50,
      overview: "Listed data center REITs and digital infrastructure operators. Prices daily against private marks that move quarterly — useful as a sanity check on the Songdo carrying value as much as an allocation.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.50%"], ["Distribution", "Semi-annual"], ["Minimum", "1 share"]],
      docs: [["Prospectus", "PDF · 74pp"]], qa: [] },
    { id: "m14", kind: "listed", name: "Macquarie Korea Infrastructure Fund", ticker: "088980.KS", fills: "infra", cls: "real",
      ret: "6.4% dividend", retNum: 6.4, liq: "Daily", term: "Listed fund", min: 1000, avail: "Continuous", fit: 81,
      why: "Regulated KRW infrastructure cash flows with daily liquidity; the only listed route into the domestic toll and tunnel base.",
      sector: "Infrastructure", geo: "Korea", ccy: "KRW", px: 13240, chg: 0.23,
      overview: "Listed closed-end fund holding 17 Korean toll roads, tunnels and a gas distribution network, most with minimum revenue guarantees. Dividend paid semi-annually and covered 1.3x by operating cash flow.",
      terms: [["Settlement", "T+2"], ["Dividend", "Semi-annual"], ["Premium / discount to NAV", "−2.8%"], ["Minimum", "1 share"]],
      docs: [["사업보고서 2025", "PDF · 180pp"]], qa: [] },
    { id: "m15", kind: "listed", name: "Brookfield Infrastructure Partners L.P.", ticker: "BIP", fills: "infra", cls: "real",
      ret: "5.9% distribution", retNum: 5.9, liq: "Daily", term: "Listed LP", min: 1000, avail: "Continuous", fit: 72,
      why: "Global diversified infrastructure; K-1 reporting adds administrative burden for a Korean-resident holder.",
      sector: "Infrastructure", geo: "Global", ccy: "USD", px: 36.15, chg: -0.18,
      overview: "Listed partnership holding utilities, transport, midstream and data infrastructure across 30 countries. Distribution growth target 5–9% annually.",
      terms: [["Settlement", "T+1"], ["Distribution", "Quarterly"], ["Tax reporting", "Schedule K-1"], ["Minimum", "1 unit"]],
      docs: [["Annual report 2025", "PDF · 168pp"]], qa: [] },

    /* ---- Everything else ---------------------------------------------- */
    { id: "m16", kind: "listed", name: "iShares iBoxx USD Investment Grade Corporate Bond ETF", ticker: "LQD", fills: "ig", cls: "debt",
      ret: "5.12% yield", retNum: 5.12, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 64,
      why: "Broad IG credit at 0.14% — duplicates exposure the book already holds in single names.",
      sector: "Corporate", geo: "United States", ccy: "USD", px: 109.74, chg: 0.11, expense: 0.14, dur: 8.3,
      overview: "Broad US investment grade corporate exposure. The book already holds this risk in single names; shown for completeness.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.14%"], ["Minimum", "1 share"]], docs: [["Prospectus", "PDF · 96pp"]], qa: [] },
    { id: "m17", kind: "listed", name: "Hanwha Life 3.95% 12-Feb-2030", ticker: "KR6088350D30", fills: "ig", cls: "debt",
      ret: "4.06% YTM", retNum: 4.06, liq: "Daily", term: "4yr", min: 100000, avail: "Secondary market", fit: 66,
      why: "Adds to issuer concentration the book already carries through the ELS note.",
      sector: "Financials", geo: "Korea", ccy: "KRW", px: 99.56, chg: 0.01, ytm: 4.06, dur: 3.3, rating: "AAA (KIS)",
      hanwha: true, anchor: "Issued by Hanwha Life Insurance.",
      overview: "Senior unsecured KRW paper from Hanwha Life. Included because it is frequently requested.",
      terms: [["Settlement", "T+1"], ["Coupon", "3.95% annual"], ["Minimum", "₩100,000,000"]], docs: [["Issue terms", "PDF · 22pp"]], qa: [] },
    { id: "m18", kind: "listed", name: "Apple Inc. 4.30% 10-May-2033", ticker: "US037833EF2", fills: "ig", cls: "debt",
      ret: "4.74% YTM", retNum: 4.74, liq: "Daily", term: "7yr", min: 10000, avail: "Secondary market", fit: 62,
      why: "Duplicates the existing 2043 Apple line at a shorter maturity.",
      sector: "Info Tech", geo: "United States", ccy: "USD", px: 96.88, chg: 0.06, ytm: 4.74, dur: 5.8, rating: "AA+",
      overview: "Intermediate Apple paper. The book already holds the 2043 line at $2.41M.",
      terms: [["Settlement", "T+1"], ["Coupon", "4.30% semi-annual"], ["Minimum", "$10,000 face"]], docs: [], qa: [] },
    { id: "m19", kind: "private", name: "Meridian Venture Partners XII — LP tranche", fills: "vc", cls: "equity",
      ret: "3.1x target net", retNum: 22.0, liq: "Locked", term: "10 years", min: 250000, avail: "$3.5M of $45M tranche", fit: 91,
      why: "Access tranche in a fund that is otherwise closed; sits inside the Alpha sleeve's remaining capacity.",
      sector: "Technology", geo: "United States", ccy: "USD", manager: "Meridian Venture Partners", closing: "2026-10-15",
      overview: "Early-stage US venture fund, twelfth vintage. Funds VIII–X are marking at 4.2x, 3.1x and 2.4x net. The tranche exists because the GP reserved capacity for platform investors; the family could not access this fund directly at a $250K commitment.",
      terms: [["Target", "3.1x net / 22% net IRR"], ["Term", "10 years + 2 one-year extensions"], ["Minimum", "$250,000"], ["Fees", "2.0% / 20% over 8%"], ["Drawdown", "Over 4 years, ~25% per year"], ["Closing", "15 October 2026"]],
      docs: [["Fund XII PPM", "PDF · 142pp"], ["Track record — Funds VIII-XI", "PDF · 24pp"], ["LPA (tranche)", "PDF · 96pp"], ["Side letter", "PDF · 6pp"]],
      qa: [["What are the drawdown mechanics?", "Approximately 25% per year over four years on 10 business days' notice. Model the commitment, not the cheque."],
           ["Can the tranche be resold?", "After a 12-month hold, on the Barbell secondary board only. The GP's consent right is pre-cleared for platform transfers."]] },
    { id: "m20", kind: "private", name: "Aeris Aerospace — Series G secondary block", fills: "preipo", cls: "equity",
      ret: "1.9x target", retNum: 18.0, liq: "Locked", term: "Until listing (est. 2028)", min: 500000, avail: "$2.8M block", fit: 87,
      why: "Averages into an existing Series F position at a 12% discount to the last primary round.",
      sector: "Aerospace", geo: "United States", ccy: "USD", manager: "Direct block", closing: "2026-10-22",
      overview: "Secondary block in a large private aerospace manufacturer, sold by an early employee holder. Priced at $186/share against the Series G primary at $211. The family holds the Series F block at $820K, entered at $142.",
      terms: [["Price", "$186.00 per share"], ["Discount to last round", "11.8%"], ["Minimum", "$500,000"], ["Transfer", "Company right of first refusal, 30 days"], ["Closing", "22 October 2026"]],
      docs: [["Company overview", "PDF · 46pp"], ["Cap table summary", "PDF · 8pp"], ["ROFR waiver process", "PDF · 4pp"], ["Audited financials 2025", "PDF · 62pp"]],
      qa: [["What if the ROFR is exercised?", "The commitment is returned in full within 5 business days. No fee."],
           ["When does this become listable?", "Twelve months after settlement, on the Barbell secondary board."]] },
    { id: "m21", kind: "private", name: "Helios AI Infrastructure SPV II", fills: "vc", cls: "equity",
      ret: "4.0x target", retNum: 28.0, liq: "Locked", term: "Exit-driven", min: 250000, avail: "$1.9M of $25M", fit: 84,
      why: "Growth-stage AI infrastructure; the family holds SPV I, marked at 1.35x after 17 months.",
      sector: "Technology", geo: "United States", ccy: "USD", manager: "Helios Partners", closing: "2026-11-01",
      overview: "Single-asset SPV into the Series D of a GPU cloud operator with $310M of contracted revenue. Concentrated: one company, one round, no diversification.",
      terms: [["Target", "4.0x"], ["Structure", "Single-asset SPV"], ["Minimum", "$250,000"], ["Fees", "0% management / 10% carry"], ["Closing", "1 November 2026"]],
      docs: [["SPV memorandum", "PDF · 28pp"], ["Company deck", "PDF · 34pp"], ["Series D term sheet", "PDF · 12pp"]],
      qa: [["How concentrated is this?", "Entirely. A $250K commitment represents 4.0% of the Alpha sleeve in a single private company."]] },
    { id: "m22", kind: "private", name: "Pacific Core Real Estate Fund V", fills: "re", cls: "real",
      ret: "8.1% target", retNum: 8.1, liq: "Quarterly", term: "Open-end", min: 500000, avail: "Open", fit: 58,
      why: "Core open-end property; the family holds Fund IV and the exposure would be duplicative.",
      sector: "Diversified RE", geo: "Asia-Pacific", ccy: "USD", manager: "Pacific Core", closing: "Quarterly close",
      overview: "Core open-end Asia-Pacific property fund. Shown because the family holds Fund IV.",
      terms: [["Target return", "8.1% net"], ["Liquidity", "Quarterly queue"], ["Minimum", "$500,000"], ["Fees", "1.0% / no carry"]],
      docs: [["PPM", "PDF · 104pp"]], qa: [] },
    { id: "m23", kind: "listed", name: "Samsung Electronics Co., Ltd.", ticker: "005930.KS", fills: "pubeq", cls: "equity",
      ret: "—", retNum: 0, liq: "Daily", term: "—", min: 1000, avail: "Continuous", fit: 55,
      why: "Already held at $1.98M; Korean technology is 11.0% of the book before adding to it.",
      sector: "Info Tech", geo: "Korea", ccy: "KRW", px: 73500, chg: -0.41,
      overview: "Held already at $1.98M, alongside SK hynix and three other semiconductor exposures.",
      terms: [["Settlement", "T+2"], ["Minimum", "1 share"]], docs: [], qa: [] },
    { id: "m24", kind: "listed", name: "Taiwan Semiconductor Mfg. (ADR)", ticker: "TSM", fills: "pubeq", cls: "equity",
      ret: "—", retNum: 0, liq: "Daily", term: "—", min: 1000, avail: "Continuous", fit: 54,
      why: "Already held; adds to semiconductor concentration that runs through four other positions.",
      sector: "Info Tech", geo: "Taiwan", ccy: "USD", px: 268.90, chg: 1.47,
      overview: "Held already at $739K.", terms: [["Settlement", "T+1"], ["Minimum", "1 share"]], docs: [], qa: [] },
    { id: "m25", kind: "listed", name: "Vanguard Total World Stock ETF", ticker: "VT", fills: "pubeq", cls: "equity",
      ret: "—", retNum: 0, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 57,
      why: "9,800 holdings at 0.06% — the cheapest single line the public sleeve could consolidate into.",
      sector: "Diversified", geo: "Global", ccy: "USD", px: 142.08, chg: 0.21, expense: 0.06,
      overview: "9,800 holdings across 49 markets. The cheapest single line the public sleeve could be consolidated into.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.06%"], ["Minimum", "1 share"]], docs: [["Prospectus", "PDF · 78pp"]], qa: [] },
    { id: "m26", kind: "listed", name: "iShares Core MSCI Emerging Markets ETF", ticker: "IEMG", fills: "pubeq", cls: "equity",
      ret: "—", retNum: 0, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 60,
      why: "Diversifies a public sleeve that is 62% Korea and US technology, without changing its size.",
      sector: "Diversified", geo: "Emerging Markets", ccy: "USD", px: 64.32, chg: 0.38, expense: 0.09,
      overview: "Emerging market exposure ex-Korea overweight. A swap candidate rather than an addition.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.09%"], ["Minimum", "1 share"]], docs: [], qa: [] },
    { id: "m27", kind: "listed", name: "Hyundai Motor Company", ticker: "005380.KS", fills: "pubeq", cls: "equity",
      ret: "—", retNum: 0, liq: "Daily", term: "—", min: 1000, avail: "Continuous", fit: 52,
      why: "Korean large cap; correlated with the operating company holding that already triggers the concentration flag.",
      sector: "Consumer Disc.", geo: "Korea", ccy: "KRW", px: 248500, chg: 0.92,
      overview: "Included in the domestic universe. Correlation to Hanmi Chemical Holdings over 3 years is 0.61.",
      terms: [["Settlement", "T+2"], ["Minimum", "1 share"]], docs: [], qa: [] },
    { id: "m28", kind: "listed", name: "SPDR Gold Shares", ticker: "GLD", fills: "comm", cls: "real",
      ret: "—", retNum: 0, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 70,
      why: "The liquid equivalent of the KRX bullion account, without the storage arrangement.",
      sector: "Precious Metals", geo: "Global", ccy: "USD", px: 412.66, chg: 0.36, expense: 0.40,
      overview: "Physically backed gold. The family holds 340g in KRX custody; GLD is the same exposure without the storage arrangement.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.40%"], ["Minimum", "1 share"]], docs: [["Prospectus", "PDF · 58pp"]], qa: [] },
    { id: "m29", kind: "listed", name: "iShares S&P GSCI Commodity-Indexed Trust", ticker: "GSG", fills: "comm", cls: "real",
      ret: "—", retNum: 0, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 61,
      why: "Broad commodity exposure; roll cost has averaged −1.8% annually over five years.",
      sector: "Commodities", geo: "Global", ccy: "USD", px: 22.14, chg: -0.22, expense: 0.75,
      overview: "Futures-based broad commodity index.", terms: [["Settlement", "T+1"], ["Expense ratio", "0.75%"]], docs: [], qa: [] },
    { id: "m30", kind: "listed", name: "Hanwha Securities ELS 2026-09 (KOSPI200 / S&P 500 autocall)", ticker: "HWELS2609", fills: "struct", cls: "debt",
      ret: "7.20% p.a. if called", retNum: 7.2, liq: "Quarterly", term: "3yr · quarterly observation", min: 100000, avail: "₩60B tranche open", fit: 79,
      why: "A replacement for the 2024-11 note, which is likely to autocall in November.",
      sector: "Structured", geo: "Korea", ccy: "KRW",
      hanwha: true, anchor: "Issued by Hanwha Securities. Hanwha Life holds ₩200B of the same series.",
      overview: "Three-year autocallable note on KOSPI200 and S&P 500 with a 55% knock-in barrier, 7.2% annual coupon if called at any quarterly observation. Principal is at risk below the barrier at maturity.",
      terms: [["Coupon", "7.20% p.a. if called"], ["Barrier", "55% knock-in, observed at maturity"], ["Observation", "Quarterly, 90/90/85/85/80/80…"], ["Minimum", "₩100,000,000"], ["Early redemption", "Quarterly at market value"]],
      docs: [["Term sheet", "PDF · 10pp"], ["Risk disclosure", "PDF · 18pp"], ["Backtest", "PDF · 6pp"]],
      qa: [["What is the historical knock-in frequency?", "On this barrier and underlier pair, 4.1% of rolling 3-year windows since 2001 ended below the barrier."]] },
    { id: "m31", kind: "listed", name: "Hanwha Principal-Protected USD/KRW Note 2026-08", ticker: "HWFX2608", fills: "struct", cls: "debt",
      ret: "0–9.5% range", retNum: 4.5, liq: "Quarterly", term: "2yr · principal protected", min: 100000, avail: "₩25B tranche open", fit: 73,
      why: "Expresses a KRW view while protecting principal — relevant given the −0.8pp QTD currency drag.",
      sector: "Structured", geo: "Korea", ccy: "KRW",
      hanwha: true, anchor: "Issued by Hanwha Securities.",
      overview: "Two-year note returning principal plus 60% of any USD/KRW appreciation above 1,380, capped at 9.5% total. Principal protected by the issuer's credit.",
      terms: [["Participation", "60% of USD/KRW upside above 1,380"], ["Cap", "9.5% total return"], ["Protection", "100% of principal at maturity, issuer credit"], ["Minimum", "₩100,000,000"]],
      docs: [["Term sheet", "PDF · 8pp"], ["Risk disclosure", "PDF · 16pp"]], qa: [] },
    { id: "m32", kind: "listed", name: "KODEX Korea REIT ETF", ticker: "329200.KS", fills: "re", cls: "real",
      ret: "5.8% dividend", retNum: 5.8, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 49,
      why: "Listed Korean REITs — duplicates direct property the family already owns outright.",
      sector: "Real Estate", geo: "Korea", ccy: "KRW", px: 5840, chg: 0.17, expense: 0.09,
      overview: "Basket of listed Korean REITs. The family already owns Korean property directly.",
      terms: [["Settlement", "T+2"], ["Expense ratio", "0.09%"]], docs: [], qa: [] },
    { id: "m33", kind: "listed", name: "iShares TIPS Bond ETF", ticker: "TIP", fills: "sov", cls: "debt",
      ret: "2.15% real", retNum: 2.15, liq: "Daily", term: "Open-ended", min: 1000, avail: "Continuous", fit: 83,
      why: "The only explicit inflation hedge available to the fixed income sleeve.",
      sector: "Government", geo: "United States", ccy: "USD", px: 108.20, chg: 0.09, expense: 0.19, dur: 6.6,
      overview: "Inflation-protected Treasuries — the only explicit inflation hedge in the fixed income sleeve.",
      terms: [["Settlement", "T+1"], ["Expense ratio", "0.19%"], ["Real yield", "2.15%"], ["Minimum", "1 share"]],
      docs: [["Prospectus", "PDF · 82pp"]], qa: [] },
  ];

  /* ----------------------------------------------------------- secondary */
  /* Bulletin board. Inventory is limited to illiquid positions originated
     on Barbell and held at least 12 months. Listed securities never appear. */
  const secondary = [
    { id: "s01", instrument: "Foundry Venture Partners VII, L.P. — LP interest", sub: "vc", cls: "equity", vintage: "2024",
      nav: 1240000, size: 620000, askPct: 92.0, indicative: [88, 95], seller: "Member #0147", days: 14, status: "Open",
      rationale: "Rebalancing toward income-producing assets ahead of a generational transfer.",
      unfunded: 820000, manager: "Foundry Venture Partners",
      account: [["2024-03-14", "Commitment", 2500000], ["2024-04-02", "Capital call #1", 625000], ["2024-11-18", "Capital call #2", 500000],
                ["2025-06-30", "Capital call #3", 400000], ["2026-06-30", "NAV mark", 1240000]] },
    { id: "s02", instrument: "Northgate Data Center Credit Facility — participation", sub: "pcred", cls: "debt", vintage: "2024",
      nav: 2000000, size: 1000000, askPct: 99.5, indicative: [98, 101], seller: "Member #0032", days: 6, status: "Open",
      rationale: "Portfolio reached its single-borrower limit following Facility II.",
      manager: "Northgate Capital Partners",
      account: [["2024-06-28", "Funded", 2000000], ["2025-06-30", "Coupon received", 184000], ["2026-06-30", "Coupon received", 188000], ["2026-08-31", "NAV mark", 2000000]] },
    { id: "s03", instrument: "Aeris Aerospace — Series E block", sub: "preipo", cls: "equity", vintage: "2023",
      nav: 1560000, size: 780000, askPct: 104.0, indicative: [99, 108], seller: "Member #0209", days: 3, status: "Open",
      rationale: "Taking partial liquidity ahead of the expected 2028 listing.",
      manager: "Direct block",
      account: [["2023-05-19", "Purchase", 900000], ["2025-11-30", "Series F mark-up", 1400000], ["2026-08-31", "NAV mark", 1560000]] },
    { id: "s04", instrument: "Sunrise Growth Partners IV, L.P. — LP interest", sub: "pe", cls: "equity", vintage: "2023",
      nav: 980000, size: 490000, askPct: 88.5, indicative: [85, 93], seller: "Member #0401", days: 31, status: "Open",
      rationale: "Consolidating manager relationships.", unfunded: 310000, manager: "Sunrise Growth Partners",
      account: [["2023-09-01", "Commitment", 1500000], ["2023-10-15", "Capital call #1", 600000], ["2024-09-30", "Capital call #2", 450000], ["2026-06-30", "NAV mark", 980000]] },
    { id: "s05", instrument: "Pacific Core Real Estate Fund IV — units", sub: "re", cls: "real", vintage: "2022",
      nav: 1420000, size: 710000, askPct: 95.0, indicative: [93, 98], seller: "Member #0147", days: 22, status: "Open",
      rationale: "Reducing Asia-Pacific property weight.", unfunded: 350000, manager: "Pacific Core",
      account: [["2022-11-04", "Commitment", 2000000], ["2023-01-20", "Capital call #1", 800000], ["2024-04-18", "Capital call #2", 600000],
                ["2025-09-30", "Distribution", -180000], ["2026-06-30", "NAV mark", 1420000]] },
    { id: "s06", instrument: "Songdo Hyperscale Data Center Platform — co-invest units", sub: "infra", cls: "real", vintage: "2025",
      nav: 2340000, size: 1170000, askPct: 101.5, indicative: [99, 104], seller: "Member #0088", days: 9, status: "Open",
      rationale: "Balance sheet rotation; no view on the asset.", manager: "Hanwha Asset Management",
      account: [["2025-02-27", "Funded", 2100000], ["2026-06-30", "NAV mark", 2340000]] },
    { id: "s07", instrument: "Meridian Direct Lending Fund II — units", sub: "pcred", cls: "debt", vintage: "2023",
      nav: 1320000, size: 660000, askPct: 97.5, indicative: [96, 99], seller: "Member #0315", days: 41, status: "Open",
      rationale: "Funding a capital call elsewhere.", manager: "Meridian Credit",
      account: [["2023-11-30", "Subscription", 1250000], ["2025-12-31", "Income reinvested", 70000], ["2026-06-30", "NAV mark", 1320000]] },
    { id: "s08", instrument: "Woori Industrial Buyout Co-Invest II — participation", sub: "pe", cls: "equity", vintage: "2022",
      nav: 1848698, size: 924000, askPct: 93.0, indicative: [90, 96], seller: "Member #0032", days: 18, status: "Open",
      rationale: "Exit expected 2029; seller's horizon is shorter.", manager: "Woori PE",
      account: [["2022-05-18", "Funded", 1400000], ["2025-06-30", "NAV mark", 1690000], ["2026-06-30", "NAV mark", 1848698]] },
    { id: "s09", instrument: "Daol Ventures Korea Fund III — LP interest", sub: "vc", cls: "equity", vintage: "2023",
      nav: 680000, size: 340000, askPct: 84.0, indicative: [80, 89], seller: "Member #0512", days: 56, status: "Open",
      rationale: "Domestic venture exposure no longer required.", unfunded: 320000, manager: "Daol Investment",
      account: [["2023-02-09", "Commitment", 1000000], ["2023-03-30", "Capital call #1", 400000], ["2024-08-14", "Capital call #2", 280000], ["2026-06-30", "NAV mark", 680000]] },
    { id: "s10", instrument: "Hanwha Korea Logistics REIT Co-Invest — units", sub: "re", cls: "real", vintage: "2024",
      nav: 1620000, size: 810000, askPct: 98.0, indicative: [96, 100], seller: "Member #0088", days: 2, status: "Open",
      rationale: "Rotating into the Co-Invest II vehicle.", manager: "Hanwha Asset Management",
      account: [["2024-09-10", "Funded", 1500000], ["2026-06-30", "NAV mark", 1620000]] },
    { id: "s11", instrument: "Helios AI Infrastructure SPV I — units", sub: "vc", cls: "equity", vintage: "2025",
      nav: 540000, size: 270000, askPct: 118.0, indicative: [110, 125], seller: "Member #0209", days: 11, status: "Settled",
      rationale: "Partial realisation after the Series D mark-up.", manager: "Helios Partners",
      account: [["2025-04-22", "Funded", 400000], ["2026-06-30", "NAV mark", 540000]] },
    { id: "s12", instrument: "Seoul Station Retail Co-Invest — participation", sub: "re", cls: "real", vintage: "2021",
      nav: 890000, size: 445000, askPct: 79.0, indicative: [74, 84], seller: "Member #0401", days: 88, status: "Open",
      rationale: "Asset has underperformed; seller is exiting the sector.", manager: "Koramco",
      account: [["2021-07-01", "Funded", 1100000], ["2024-06-30", "NAV mark", 960000], ["2026-06-30", "NAV mark", 890000]] },
  ];

  /* Two listings open with a bid already sitting with the seller. A bid does
     not change the listing's state — it stays open to anyone taking the ask. */
  const bidsSeed = [
    { id: "b1", listingId: "s04", price: 85.0, size: 300000, ts: "2026-09-15T10:20:00+09:00",
      bidder: "Member #0233", status: "Submitted" },
    { id: "b2", listingId: "s07", price: 96.0, size: 400000, ts: "2026-09-11T14:05:00+09:00",
      bidder: "Member #0512", status: "Submitted" },
  ];

  /* ------------------------------------------------------------ approvals */
  const approvalsSeed = [
    { id: "a1", ts: "2026-09-17T11:22:00+09:00", from: "successor", type: "Commitment",
      title: "Commit $1,000,000 to Northgate Data Center Credit Facility II",
      target: "m06", amount: 1000000, sleeve: "core",
      rationale: "9.2% senior secured on the same security package as the Facility I position we already hold, which is performing. Above the Alpha sleeve's $760,000 capacity, so it is submitted rather than executed.",
      status: "pending" },
    { id: "a2", ts: "2026-09-12T09:05:00+09:00", from: "successor", type: "Trade",
      title: "Buy $420,000 iShares 7-10 Year Treasury Bond ETF (IEF) in Core",
      target: "m03", amount: 420000, sleeve: "core",
      rationale: "The fixed income sleeve is short duration against the policy. This is the fastest instrument to lengthen it while a direct ladder is built.",
      status: "pending" },
    { id: "a3", ts: "2026-08-28T16:40:00+09:00", from: "successor", type: "Commitment",
      title: "Commit $250,000 to Helios AI Infrastructure SPV II",
      target: "m21", amount: 250000, sleeve: "alpha",
      rationale: "Follow-on to SPV I at a 1.35x mark.",
      status: "approved", decidedTs: "2026-08-29T08:15:00+09:00", comment: "Approved. Keep single-company exposure under 5% of the sleeve." },
    { id: "a4", ts: "2026-08-14T13:12:00+09:00", from: "successor", type: "Trade",
      title: "Sell $600,000 Apple Inc. 3.85% 2043 from Core",
      target: "p23", amount: 600000, sleeve: "core",
      rationale: "Duration is long and the position is below cost.",
      status: "returned", decidedTs: "2026-08-15T10:02:00+09:00",
      comment: "Returned. Selling at a loss to fund a position we already hold twice over is the wrong order of operations. Resubmit with the proceeds directed to sovereign duration." },
  ];

  /* ------------------------------------------------------------- activity */
  const activitySeed = [
    { id: "l1", ts: "2026-09-18T16:31:00+09:00", who: "successor", kind: "Valuation", text: "Updated valuation for Viva Republica (Toss) common — 2023 block", detail: "No change to carrying value; flagged as stale pending a Q3 statement." },
    { id: "l2", ts: "2026-09-17T11:22:00+09:00", who: "successor", kind: "Proposal", text: "Submitted proposal — Commit $1,000,000 to Northgate Data Center Credit Facility II", detail: "Exceeds Alpha sleeve capacity of $760,000. Routed to the Principal." },
    { id: "l3", ts: "2026-09-16T10:14:00+09:00", who: "principal", kind: "Mandate", text: "Confirmed target allocation — Balanced (90/10)", detail: "Equity 35.0 · Debt 40.0 · Real Assets 18.0 · Cash 7.0" },
    { id: "l4", ts: "2026-09-12T09:05:00+09:00", who: "successor", kind: "Proposal", text: "Submitted proposal — Buy $420,000 IEF in Core", detail: "A Core sleeve trade — only the Principal can approve it." },
    { id: "l5", ts: "2026-09-08T14:48:00+09:00", who: "principal", kind: "Trade", text: "Bought 2,000 shares NVIDIA Corporation", detail: "$428,000 at $214.00. Core sleeve. Settled same day." },
    { id: "l6", ts: "2026-09-02T09:30:00+09:00", who: "system", kind: "Capital call", text: "Capital call received — Foundry Venture Partners VII, $1,100,000", detail: "Due 28 October 2026. Added to the liquidity projection." },
    { id: "l7", ts: "2026-08-31T18:00:00+09:00", who: "system", kind: "Valuation", text: "Hanwha-sourced NAVs refreshed for 9 positions", detail: "As of 30 June 2026 capital accounts." },
    { id: "l8", ts: "2026-08-29T08:15:00+09:00", who: "principal", kind: "Approval", text: "Approved proposal — Commit $250,000 to Helios AI Infrastructure SPV II", detail: "Comment: keep single-company exposure under 5% of the sleeve." },
    { id: "l9", ts: "2026-08-15T10:02:00+09:00", who: "principal", kind: "Approval", text: "Returned proposal — Sell $600,000 Apple 3.85% 2043", detail: "Returned with comment for resubmission." },
    { id: "l10", ts: "2026-08-04T11:40:00+09:00", who: "successor", kind: "Commitment", text: "Committed $250,000 to Meridian Venture Partners XII", detail: "Within Alpha sleeve capacity. Executed directly." },
    { id: "l11", ts: "2026-07-22T15:05:00+09:00", who: "principal", kind: "Onboarding", text: "Portfolio ingestion completed — 42 positions mapped", detail: "3 source files. 3 exceptions resolved by the Principal." },
  ];

  /* ------------------------------------------------ operations (internal) */
  const opsLedger = [
    { id: "x1", ts: "2026-09-08T14:48:12+09:00", instr: "NVDA", desc: "NVIDIA Corporation", qty: "2,000", ref: "BBL-2026-0908-0041", finality: "2026-09-08T14:48:14+09:00", state: "Final" },
    { id: "x2", ts: "2026-08-04T11:40:02+09:00", instr: "MVP-XII-T", desc: "Meridian Venture Partners XII tranche", qty: "$250,000", ref: "BBL-2026-0804-0018", finality: "2026-08-04T11:40:04+09:00", state: "Final" },
    { id: "x3", ts: "2026-06-30T23:59:58+09:00", instr: "SONGDO-I", desc: "Songdo Hyperscale DC Platform — NAV update", qty: "—", ref: "BBL-2026-0630-0902", finality: "2026-06-30T23:59:59+09:00", state: "Final" },
    { id: "x4", ts: "2026-05-22T10:02:31+09:00", instr: "HELIOS-I", desc: "Helios AI Infrastructure SPV I", qty: "$400,000", ref: "BBL-2026-0522-0007", finality: "2026-05-22T10:02:33+09:00", state: "Final" },
    { id: "x5", ts: "2026-01-10T09:14:07+09:00", instr: "HKLR-I", desc: "Hanwha Korea Logistics REIT Co-Invest", qty: "$1,500,000", ref: "BBL-2026-0110-0003", finality: "2026-01-10T09:14:09+09:00", state: "Final" },
  ];

  const referrals = { sent: 3, joined: 1,
    invites: [
      { id: "r1", to: "Member of Daesan family office", deal: "Northgate Data Center Credit Facility II", ts: "2026-09-10", state: "Viewed" },
      { id: "r2", to: "S.H. Chung", deal: "Meridian Venture Partners XII", ts: "2026-08-22", state: "Joined" },
      { id: "r3", to: "Kwon family office", deal: "Songdo Hyperscale DC Platform II", ts: "2026-07-30", state: "Sent" },
    ] };

  const liquidityAssumptions = { monthlyIncome: 95000, monthlySpend: 120000, reserveFloor: 1500000 };

  window.BB = window.BB || {};
  BB.data = {
    KRW, TODAY, family, accounts, classes, subs, positions,
    uploadFiles, ingestSteps, exceptions, mandates, survey, modelPortfolios,
    capitalCalls, distributions, benchmark, performance, attribution, modelGoals, ALT_SUBS, expectedReturn, expectedVol, classCorr, idiosyncraticVol,
    market, secondary, bidsSeed, approvalsSeed, activitySeed, opsLedger, referrals, liquidityAssumptions,
  };
})();
